import React from 'react';
import { Box, Typography, Paper, Divider } from '@mui/material';

/**
 * PostgreSQL-specific help panel for explain plans
 */
const PostgreSQLHelpPanel = () => {
  return (
    <Paper sx={{ p: 2, mb: 2, bgcolor: '#f8f9fa' }}>
      <Typography variant="subtitle2" gutterBottom>Understanding PostgreSQL Explain Plans</Typography>
      <Typography variant="body2" sx={{ mb: 1 }}>
        PostgreSQL EXPLAIN shows the query execution plan generated by the query planner. Key elements to focus on:
      </Typography>
      
      <Box component="ul" sx={{ mt: 0, pl: 3 }}>
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Node Type:</strong> The operation type, such as:
            <Box component="ul" sx={{ pl: 3 }}>
              <Box component="li">
                <Typography variant="body2" component="span">
                  <code>Seq Scan</code>: Full table scan (often inefficient for large tables)
                </Typography>
              </Box>
              <Box component="li">
                <Typography variant="body2" component="span">
                  <code>Index Scan/Index Only Scan</code>: Using an index to access data (generally efficient)
                </Typography>
              </Box>
              <Box component="li">
                <Typography variant="body2" component="span">
                  <code>Bitmap Heap/Index Scan</code>: Two-phase scan using a bitmap in memory
                </Typography>
              </Box>
              <Box component="li">
                <Typography variant="body2" component="span">
                  <code>Nested Loop/Hash/Merge Join</code>: Different join algorithms with varying performance characteristics
                </Typography>
              </Box>
            </Box>
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Cost:</strong> Estimated cost of the operation (higher values indicate more expensive operations).
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Rows:</strong> Estimated number of rows the operation will produce.
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Actual Time:</strong> When using <code>EXPLAIN ANALYZE</code>, shows the actual execution time in milliseconds.
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Actual Rows:</strong> The actual number of rows produced during execution.
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Loops:</strong> Number of times this node was executed.
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Filter/Index Cond:</strong> Conditions applied to filter rows (watch for functions on indexed columns).
          </Typography>
        </Box>
        
        <Box component="li">
          <Typography variant="body2" component="div">
            <strong>Width:</strong> Estimated size (in bytes) of each row.
          </Typography>
        </Box>
      </Box>
      
      <Divider sx={{ my: 1.5 }} />
      
      <Typography variant="subtitle2" gutterBottom>Performance Warning Signs</Typography>
      <Box component="ul" sx={{ mt: 0, pl: 3 }}>
        <Box component="li">
          <Typography variant="body2" component="div">
            <code>Seq Scan</code> on large tables without appropriate WHERE conditions
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            Large difference between estimated and actual rows (indicates statistics need updating)
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            <code>Sort</code> operations with high memory usage (check work_mem setting)
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            <code>Materialize</code> or <code>Sort</code> operations that could be avoided
          </Typography>
        </Box>
      </Box>
      
      <Divider sx={{ my: 1.5 }} />
      
      <Typography variant="subtitle2" gutterBottom>Optimization Tips</Typography>
      <Box component="ul" sx={{ mt: 0, pl: 3 }}>
        <Box component="li">
          <Typography variant="body2" component="div">
            Create appropriate indexes for query patterns
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            Run <code>ANALYZE</code> regularly to update statistics
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            Consider <code>EXPLAIN ANALYZE</code> to see actual execution metrics
          </Typography>
        </Box>
        <Box component="li">
          <Typography variant="body2" component="div">
            Adjust <code>work_mem</code> if seeing many disk-based operations
          </Typography>
        </Box>
      </Box>
      
      <Typography variant="body2" sx={{ mt: 1.5, fontStyle: 'italic' }}>
        <strong>Tip:</strong> Hover over column headers for more detailed explanations.
      </Typography>
    </Paper>
  );
};

export default PostgreSQLHelpPanel;
